name: radler-local

channels:
  # Keep in this order!
  - fastai
  - pytorch
  - defaults
  - conda-forge
  - gpytorch
  - plotly
  - gurobi
  - mosek
  - oxfordcontrol
  - albumentations
  - comet_ml
  - cvxgrp
  - intel

dependencies:
  ### LATEST-PINNED ###
  # Keep Python pinned, but in sync with latest version.!
  - python=3.7.7
  # Use MKL to provide BLAS, latest version from the defaults channel.
  - blas=*=mkl
  - mkl-service
  - intel-openmp
  - mkl
  # Pin OSQP to the latest version (must be hand-picked) from the dedicated channel.
  - osqp=0.6.1
  # Pin redis-py to latest version (must be hand-picked) from conda-forge
  - redis-py=3.4.1
  ### BOUND-PINNED ###
  # Pin tqdm for PyTorch Lightning
  - tqdm>=4.35
  ### FIX-PINNED ###
  # Pin opt_einsum to a tagged version, synced with the latest version
  - opt_einsum=3.2.1
  # Pin PIL/Pillow to the same version as pillow-simd (must be hand-picked).
  - pillow=7.0
  # Pin NetworkX to version 2.2 (req. by HyperOpt)
  - networkx=2.4
  # Pin FlatBuffers (req. by PyProb)
  - flatbuffers=1.12
  # Pin ThinC dependencies
  - cython-blis=0.4.1
  - cymem=2.0.3
  - murmurhash=1.0.2
  - preshed=3.0.2
  - pydantic=1.5.1
  - wasabi=0.6
  - immutables=0.12
  # PyTorch and the like
  - pytorch=1.4
  - captum=0.2
    # Optimization-related stuff
  - ecos=2.0.7.post1
  - scs=2
  # Minimal but useful TensorFlow 2+ setup
  - tensorflow-gpu=2.1
  - tensorflow-estimator=2.1
  ### UNPINNED ###
  # All the rest; add alphabetically.
  - absl-py
  - aiohttp
  - albumentations
  - alembic
  - appdirs
  - argh
  - args
  - async-timeout
  - atomicwrites
  - attrs
  - awkward
  - awkward-numba
  - backcall
  - bayesian-optimization
  - bleach
  - blessings
  - bokeh
  - botorch
  - category_encoders
  - certifi
  - cffi
  - chardet
  - click
  - cliff
  - clint
  - cloudpickle
  - cmd2
  - colorama
  - colorlog
  - comet-git-pure
  - comet_ml
  - conda
  - configobj
  - contextlib2
  - coverage
  - cycler
  - cython
  - ddt
  - decorator
  - defusedxml
  - dill
  - docker-pycreds
  - docutils
  - emcee
  - entrypoints
  - everett
  - fastai
  - fastcache
  - fastprogress
  - fastrlock
  - filelock
  - flask
  - flask-cors
  - funcsigs
  - future
  - gitdb2
  - gitpython
  - gpytorch
  - graphene
  - graphviz
  - grpcio
  - gurobi
  - gql
  - graphql-core
  - graphql-server-core
  - h5py
  - hdf5
  - hickle
  - idna
  - imageio
  - imgaug
  - importlib_metadata
  - ipdb
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jedi
  - jinja2
  - joblib
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_launcher
  - jupyterlab_server
  - jupytext
  - kiwisolver
  - libjpeg-turbo
  - Mako
  - MarkupSafe
  - matplotlib
  - mistune
  - mkdocs
  - mock
  - monkeytype
  - more-itertools
  - mosek
  - moviepy
  - multidict
  - multipledispatch
  - multiprocess
  - mypy
  - mypy_extensions
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - netifaces
  - nlopt
  - nose
  - notebook
  - numba
  - numpy
  - oauthlib
  - onnx
  - opencv
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pathtools
  - patsy
  - pbr
  - pexpect
  - pickleshare
  - pip
  - plotly
  - pluggy
  - PrettyTable
  - prometheus_client
  - promise
  - prompt_toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pyarrow
  - pybind11
  - pycparser
  - pydot
  - pydotplus
  - pygments
  - pymongo
  - pypandoc
  - pyparsing
  - pyperclip
  - pyro4
  - pyrsistent
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - python-dateutil
  - python-graphviz
  - pytz
  - pyyaml
  - pyzmq
  - qtconsole
  - rdflib
  - redis
  - regex
  - requests
  - retrying
  - rply
  - rx
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - scipy
  - seaborn
  - send2trash
  - sentry-sdk
  - serpent
  - setuptools
  - shortuuid
  - simplegeneric
  - six
  - skorch
  - skrebate
  - smmap2
  - spacy
  - srsly
  - structlog
  - swig
  - sympy
  - sqlalchemy
  - statsmodels
  - stevedore
  - tabulate
  - tensorboardx
  - tensorly
  - termcolor
  - terminado
  - testpath
  - toolz
  - torchaudio
  - torchfile
  - torchtext
  - torchvision
  - tornado
  - traitlets
  - twine
  - typing
  - typing_extensions
  - tzlocal
  - urllib3
  - urwid
  - visdom
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - widgetsnbextension
  - wurlitzer
  - xmltodict
  - yarl
  - zipp
  - docopt
  - jsonpickle
  - munch
  - wrapt
  - py-cpuinfo
  - PyJWT
  - flask-compress
  - path.py
  - jmespath
  - dask
  - dask-core
  - xarray
  - alabaster
  - babel
  - distributed
  - heapdict
  - imagesize
  - snowballstemmer
  - sortedcontainers
  - tblib
  - zict
  - oset
  - descartes
  - pyglet
  - jupyterthemes
  - jupyter_nbextensions_configurator
  - mpmath

  # NOTE:
  # Due to peculiar packaging of Anaconda's `opt-einsum`, the package gets reinstalled
  # by pip dependencies installation below. The Anaconda-installed package is removed
  # beforehand. This causes no harm whatsoever, apart from having to re-donwload and
  # reinstall the package. However, it's the most straightforward workaround.

  - pip:
      # Keep in this order; add at the bottom.
      - git+https://github.com/twiecki/CythonGSL.git
      - git+https://github.com/pytorch/ignite.git
      - git+https://github.com/pytorch/contrib.git
      - git+https://github.com/pytorch/tnt.git
      - tensorflow_probability
      - gin-config
      - fasteners
      - monotonic
      - cachetools
      - pyasn1
      - pyasn1-modules
      - rsa
      - google-auth
      - sentencepiece
      - py
      - cma
      - configparser
      - sklearn
      - sklearn2
      - test_tube
      - git+https://github.com/facebookresearch/nevergrad.git
      - torchviz
      - git+https://github.com/torchgan/torchgan.git
      - torchfusion
      - git+https://github.com/IBM/adversarial-robustness-toolbox.git
      - ax-platform
      - optuna
      - https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp37-cp37m-manylinux1_x86_64.whl
      - git+https://github.com/Luolc/AdaBound.git
      - https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.45-cp37-none-linux_x86_64.whl
      - jax==0.1.64
      - randomgen
      - git+https://github.com/BorealisAI/advertorch.git
      - git+https://github.com/bethgelab/foolbox.git
      - git+https://github.com/oxfordcontrol/osqpth.git
      - git+https://github.com/locuslab/qpth.git
      - git+https://github.com/bamos/block.git
      - git+https://github.com/facebookresearch/qhoptim.git
      - observations
      - unification
      - git+https://github.com/pyro-ppl/pyro-api.git
      - git+https://github.com/pyro-ppl/pyro.git
      - git+https://github.com/pyro-ppl/numpyro.git
      - git+https://github.com/pyro-ppl/funsor.git
      - git+https://github.com/pyro-ppl/brmp.git
      - git+https://github.com/emaballarin/pyro-models.git
      - git+https://github.com/harvardnlp/namedtensor
      # zmq is a "fake dependency"
      - zmq
      - wolframclient
      - git+https://github.com/NeuralEnsemble/lazyarray.git
      - git+https://github.com/TimDettmers/sparse_learning.git
      - git+https://github.com/GRAAL-Research/poutyne.git
      - git+https://github.com/hyperopt/hyperopt.git
      - git+https://github.com/hyperopt/hyperopt-sklearn.git
      - astor
      - git+https://github.com/vlasovskikh/funcparserlib.git
      - art
      - livelossplot
      - pycm
      - git+https://github.com/pytorchbearer/torchbearer
      - git+https://github.com/pytorchbearer/visual
      - git+https://github.com/pytorchbearer/variational
      - python_version
      - git+https://github.com/AI-DI/Brancher.git
      - git+https://github.com/sksq96/pytorch-summary.git
      - git+https://github.com/pyprob/pyprob.git
      - git+https://github.com/achaiah/pywick.git
      - git+https://github.com/unit8co/vegans.git
      - rpy2
      - googledrivedownloader
      - plyfile
      - nvidia-ml-py3
      - git+https://github.com/fbcotter/py3nvml.git
      - git+https://github.com/MadryLab/cox.git
      - git+https://github.com/afq984/python-cxxfilt.git
      - git+https://github.com/cybertronai/pytorch-fd.git
      - git+https://github.com/cybertronai/pytorch-lamb.git
      - git+https://github.com/gbaydin/hypergradient-descent.git
      - git+https://github.com/digantamisra98/Echo.git
      - git+https://github.com/msmbuilder/osprey.git
      - tableprint
      - GPUtil
      - git+https://github.com/MadryLab/robustness.git
      - git+https://github.com/clbarnes/f_it.git
      - git+https://github.com/numenta/nupic.torch.git
      - git+https://github.com/wookayin/gpustat.git
      - git+https://github.com/ahug/setGPU.git
      - flask-graphql
      - wandb
      - git+https://github.com/drvinceknight/Nashpy.git
      - git+https://github.com/automl/ConfigSpace.git
      - pynisher
      - pyrfr
      - sobol_seq
      - lazy_import
      - pyDOE
      - git+https://github.com/automl/SMAC3.git
      - imbalanced-learn
      - git+https://github.com/automl/HpBandSter.git
      - liac-arff
      - openml
      - tensorboard_logger
      - git+https://github.com/automl/Auto-PyTorch.git
      - git+https://github.com/automl/pybnn.git
      - git+https://github.com/cool-RR/PySnooper.git
      - git+https://github.com/floringogianu/augment.git
      - git+https://github.com/tudor-berariu/liftoff.git
      - http://ballarin.cc/mirrorsrv/artelysknitro/knitropython.tar.gz
      - git+https://github.com/ElementAI/baal.git
      - git+https://github.com/FenTechSolutions/CausalDiscoveryToolbox.git
      - dataclasses
      - contextvars
      - catalogue
      - ml_datasets
      - thinc==8.0.0a1
      - omegaconf
      - git+https://github.com/tristandeleu/pytorch-meta.git
      - frozendict
      - git+https://github.com/LiyuanLucasLiu/RAdam.git
      - git+https://github.com/rtqichen/torchdiffeq.git
      - git+https://github.com/facebookresearch/higher.git
      - git+https://github.com/uber-research/TuRBO.git
      - git+https://github.com/uber-research/EvoGrad.git
      - git+https://github.com/facebookresearch/jacobian_regularizer.git
      - git+https://github.com/facebookresearch/FDR_scheduler.git
      - git+https://github.com/facebookresearch/qhoptim.git
      - git+https://github.com/google/neural-tangents.git
      - git+https://github.com/pgmpy/pgmpy.git
      - executing
      - asttokens
      - git+https://github.com/gruns/icecream.git
      - cheap_repr
      - git+https://github.com/alexmojaki/snoop.git
      - git+https://github.com/zasdfgbnm/TorchSnooper.git
      - argparse
      - corner
      - glmnet
      - py-spy
      - git+https://github.com/mariogeiger/hessian.git
      - sacred
      - bravado
      - requests-oauthlib
      - neptune-client
      - neptune-notebooks
      - attrdict
      - scikit-plot
      - botocore
      - s3transfer
      - boto3
      - altair
      - aif360
      - beautifulsoup4
      - soupsieve
      - hiplot
      - neptune-contrib
      - cvxpy
      - threadpoolctl
      - git+https://github.com/cvxgrp/dccp.git
      - git+https://github.com/cvxgrp/sccf.git
      - git+https://github.com/cvxgrp/a2dr.git
      - git+https://github.com/cvxgrp/dmcp.git
      - git+https://github.com/cvxgrp/cone_prog_refine.git
      - git+https://github.com/cvxgrp/strat_models.git
      - dm-tree
      - git+https://github.com/deepmind/dm_env.git
      - git+https://github.com/deepmind/dm-haiku.git
      - git+https://github.com/deepmind/rlax.git
      - git+https://github.com/arogozhnikov/einops.git
      - git+https://github.com/google/pasta.git
      - git+https://github.com/google/edward2.git#egg=edward2
      - git+https://github.com/google/TensorNetwork.git
      - celluloid
      - git+https://github.com/AdamCobb/hamiltorch.git
      - git+https://github.com/MilesCranmer/differentiable_quantile_transform.git
      - git+https://github.com/robertness/pyro_agents.git
      - ipyparallel
      - msgpack
      - latexcodec
      - pybtex
      - pybtex-docutils
      - sphinx
      - sphinxcontrib-applehelp
      - sphinxcontrib-devhelp
      - sphinxcontrib-htmlhelp
      - sphinxcontrib-jsmath
      - sphinxcontrib-qthelp
      - sphinxcontrib-serializinghtml
      - sphinxcontrib-bibtex
      - fastscript
      - nbdev
      # Following two only local install!
      - cmdstanpy
      - pystan
      - bayespy
      - pgmpy
      - git+https://github.com/openai/gym.git
      - PyPubSub
      - bencode.py
      - bitstring
      - academictorrents
      - cryptography
      - adal
      - isodate
      - git+https://github.com/Mirko-Nava/BayesianNeuralNetworks.git
      - littleutils
      - outdated
      - pandas_flavor
      - git+https://github.com/raphaelvallat/pingouin.git
      - git+https://github.com/jonasrauber/eagerpy.git
      - git+https://github.com/bethgelab/foolbox.git
      - git+https://github.com/szymonmaszke/torchlayers.git
      - git+https://github.com/szymonmaszke/torchfunc.git
      - git+https://github.com/szymonmaszke/torchdata.git
      - git+https://github.com/davidtvs/pytorch-lr-finder.git
      - retry
      - mysql-connector-python
      - doltpy
